#!/usr/bin/env bash

set -u -o pipefail

result=0

for dir in $(find . -mindepth 1 -type d); do
	test=$(basename $dir)

	echo -n "$test: "
	./run $test

	if [[ $? == 0 ]]; then
		echo OK
	else
		echo FAIL
		result=1
	fi
done

exit $result
