services:
  left:
    image: postgres:latest
    container_name: postgres-left
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8901:5432
    restart: unless-stopped
  right:
    image: postgres:latest
    container_name: postgres-right
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8902:5432
    restart: unless-stopped
