name: Build

on:
  pull_request:
    paths:
      - Cargo.toml
      - src
      - README.md
      - LICENSE

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose
