name: Release

on:
  push:
    branch:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Tag
      id: tag
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main

    - name: Version
      run: |
        sed -i "s/^version.*/version = \"${{ steps.tag.outputs.new_version }}\"/" Cargo.toml

    - name: Build
      run: cargo build --release --verbose

    - name: Archive
      run: |
        mkdir lbdt-${{ github.ref_name}}
        mv LICENSE README.md target/release/lbdt lbdt-${{ github.ref_name }}
        tar -czf lbdt-${{ github.ref_name }}.tgz lbdt-${{ github.ref_name }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        name: ${{ steps.tag.outputs.new_tag }}
        generate_release_notes: true
        files: lbdt-${{ github.ref_name }}.tgz
